server:
  port: ${SERVER_PORT:8094}

spring:
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME:root}:${DB_PASSWORD:toor}@${DB_HOST:localhost}:${DB_PORT:27017}/${DB_NAME:plazoleta_tracking_db}?authSource=admin
  application:
    name: tracking-microservice

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  user: ${JWT_USER:AUTH0JWT_BACKEND}
  expiration: ${JWT_EXPIRATION:86400000}

# Uncomment the following lines to enable debug logging

logging:
  level:
    '[org.springframework.data.mongodb]': DEBUG
    '[org.mongodb.driver]': DEBUG