server:
  port: ${SERVER_PORT:8094}

spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:plazoleta_tracking_db}
      username: ${DB_USERNAME:root}
      password: ${DB_PASSWORD:toor}
      authentication-database: admin
  application:
    name: tracking-microservice

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  user: ${JWT_USER:AUTH0JWT_BACKEND}
  expiration: ${JWT_EXPIRATION:86400000}

# Uncomment the following lines to enable debug logging

# logging:
#  level:
#    root: debug

foodcourt-microservice:
  url: http://localhost:8092